# Generated by Django 2.2.1 on 2019-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grouping',
            field=models.CharField(blank=True, choices=[('F', 'free'), ('M', 'monetary'), ('P', 'published')], default='F', max_length=50),
        ),
    ]
