# Generated by Django 2.2.1 on 2019-06-26 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=datetime.datetime(2019, 6, 26, 10, 41, 39, 281598, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('published', 'Published')], default='draft', max_length=60)),
            ],
        ),
    ]
