# Generated by Django 2.2.1 on 2019-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20190611_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='fname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
