# Generated by Django 2.2.1 on 2019-06-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20190611_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nick_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
