# Generated by Django 2.2.1 on 2019-06-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20190612_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='summary',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
